#!/usr/bin/env python3
"""Build a deterministic public-method handbook from Scala 3 Scaladoc HTML.

No third-party Python dependencies. This consumes compiler-rendered signatures,
not regexes over Scala source. Call templates are illustrative, not runnable tests.
"""
from __future__ import annotations

import argparse
from collections import defaultdict
from html.parser import HTMLParser
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys

MARKER = "<!-- Generated by tools/docs/build_reference.py; do not edit. -->"
VOID = {"area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source", "track", "wbr"}


class Node:
    def __init__(self, tag="root", attrs=()):
        self.tag, self.attrs, self.children = tag, dict(attrs), []

    def has(self, cls):
        return cls in self.attrs.get("class", "").split()

    def walk(self):
        yield self
        for child in self.children:
            if isinstance(child, Node):
                yield from child.walk()

    def first(self, cls):
        return next((n for n in self.walk() if n.has(cls)), None)

    def text(self):
        return "".join(c.text() if isinstance(c, Node) else c for c in self.children)


class DocParser(HTMLParser):
    """Keep only #content, avoiding the large repeated navigation tree."""
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.root = Node()
        self.stack = []

    def handle_starttag(self, tag, attrs):
        if not self.stack:
            if dict(attrs).get("id") != "content":
                return
            node = Node(tag, attrs)
            self.root.children.append(node)
            self.stack.append(node)
            return
        node = Node(tag, attrs)
        self.stack[-1].children.append(node)
        if tag not in VOID:
            self.stack.append(node)

    def handle_endtag(self, tag):
        for i in range(len(self.stack) - 1, -1, -1):
            if self.stack[i].tag == tag:
                del self.stack[i:]
                return

    def handle_data(self, data):
        if self.stack:
            self.stack[-1].children.append(data)


def clean(text):
    return re.sub(r"\s+", " ", text).strip()


def split_top(text, delimiter=","):
    """Split while preserving nested generics/functions/refinements/default strings."""
    depth, quote, escaped, start, result = [], None, False, 0, []
    for i, char in enumerate(text):
        if quote:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quote:
                quote = None
            continue
        if char in ('"', '`'):
            quote = char
        elif char in "([{":
            depth.append(char)
        elif char in ")]}":
            if depth:
                depth.pop()
        elif char == delimiter and not depth:
            result.append(text[start:i].strip())
            start = i + 1
    result.append(text[start:].strip())
    return result


def take_group(text):
    opening = text[0]
    closing = {"[": "]", "(": ")"}[opening]
    depth, quote, escaped = 0, None, False
    for i, char in enumerate(text):
        if quote:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quote:
                quote = None
            continue
        if char in ('"', '`'):
            quote = char
        elif char == opening:
            depth += 1
        elif char == closing:
            depth -= 1
            if depth == 0:
                return text[1:i].strip(), text[i + 1:].strip()
    raise ValueError(f"Unbalanced signature: {text}")


def signature_parts(signature, name):
    match = re.search(r"\bdef\s+" + re.escape(name) + r"(?=\s|\[|\(|:|$)", signature)
    if not match:
        raise ValueError(f"Cannot find method {name}: {signature}")
    rest = signature[match.end():].strip()
    types, groups = [], []
    if rest.startswith("["):
        group, rest = take_group(rest)
        types = split_top(group)
    while rest.startswith("("):
        group, rest = take_group(rest)
        contextual = group.startswith("implicit ") or group.startswith("using ")
        group = re.sub(r"^(implicit|using)\s+", "", group)
        groups.append({"contextual": contextual, "parameters": split_top(group) if group else []})
    if name == "this" and not rest:
        return types, groups, "<constructed instance>"
    if not rest.startswith(":"):
        raise ValueError(f"Missing compiler return type: {signature}")
    return types, groups, rest[1:].strip()


def invocation(owner, is_object, name, types, groups):
    type_names = [re.split(r"[\s\[:<>=]", t.lstrip("+-"))[0] for t in types]
    receiver = owner if is_object else "receiver"
    call = "new " + owner if name == "this" else receiver + "." + name
    if type_names:
        call += "[" + ", ".join(type_names) + "]"
    for group in groups:
        args = []
        for i, declaration in enumerate(group["parameters"]):
            bits = split_top(declaration, ":")
            arg = re.sub(r"^(inline|erased|val|var)\s+", "", bits[0]).strip()
            if len(bits) < 2 or arg == "_":
                arg = f"argument{i + 1}"
            type_text = ":".join(bits[1:]).split(" = ", 1)[0].strip()
            if type_text.endswith("*"):
                arg += "*"
            args.append(arg)
        call += "(" + ("using " if group["contextual"] else "") + ", ".join(args) + ")"
    return call


def extract(path):
    parser = DocParser()
    parser.feed(path.read_text(encoding="utf-8"))
    root = parser.root
    fq = root.first("fqname")
    header = root.first("main-signature")
    if fq is None or header is None:
        return [], 0
    owner = clean(fq.text())
    is_object = bool(re.search(r"\bobject\b", clean(header.text())))
    methods, excluded = [], 0
    for node in root.walk():
        if not node.has("documentableElement"):
            continue
        signature = node.first("signature")
        name_node = signature.first("documentableName") if signature else None
        if name_node is None:
            continue
        text = clean(signature.text())
        if not re.search(r"\bdef\s", text):
            continue
        if re.search(r"\b(private|protected)\b", text.split("def ", 1)[0]):
            excluded += 1
            continue
        name = clean(name_node.text())
        types, groups, returns = signature_parts(text, name)
        if name == "this":
            returns = owner
        brief = node.first("documentableBrief")
        # Scaladoc's full .cover may contain prose, parameter descriptions,
        # return descriptions, examples, and exception/deprecation attributes.
        cover = node.first("cover")
        methods.append({"owner": owner, "name": name, "anchor": node.attrs["id"],
                        "signature": text, "type_parameters": types, "parameter_lists": groups,
                        "returns": returns, "summary": clean(brief.text()) if brief else "",
                        "contract": clean(cover.text()) if cover else "",
                        "example": invocation(owner, is_object, name, types, groups),
                        "object": is_object})
    return methods, excluded


def markdown_code(text):
    # Method signatures can contain backticked identifiers.
    return "`` " + text + " ``"


def render(api, output):
    groups = defaultdict(list)
    inventory, excluded, page_count = [], 0, 0
    for page in sorted((api / "com" / "cra" / "figaro").rglob("*.html")):
        methods, hidden = extract(page)
        excluded += hidden
        page_count += 1
        for method in methods:
            method["page"] = page.relative_to(api).as_posix()
            inventory.append(method)
            groups[page.relative_to(api).parent.as_posix()].append(method)
    if not inventory:
        raise ValueError("No public methods found; generate Scala 3 Scaladoc first")
    files = {}
    index = [MARKER, "# Complete public-method reference", "",
             "[User guide](../USER_GUIDE.md) · [Practical API guide](../API_GUIDE.md) · [Build instructions](../BUILDING.md)", "",
             f"Compiler-derived inventory: **{len(inventory)} public method entries** from **{page_count} Scala 3 API pages**. "
             f"Excluded {excluded} protected/private method entries. Overloads have separate entries.", "",
             "Scope: every public `def` exposed on the generated `com.cra.figaro` API pages, including abstract methods and "
             "compiler-generated methods shown by Scaladoc. Inherited members are included wherever Scaladoc renders them. "
             "Fields, type aliases, primary constructor signatures, inheritance diagrams, and members hidden by Scaladoc "
             "remain available in the linked full API site; this handbook does not reclassify them as functions.", "",
             "Each entry gives the compiler signature, type/value/context parameters, return type, available source contract, "
             "and an **invocation template**. Templates assume appropriately typed variables/type arguments and an existing "
             "receiver; they are not standalone programs or independently executed tests. Some low-level APIs require "
             "subclass/inference-engine context. Use the tested complete examples in the user guide to begin.", "",
             "Missing behavioral prose is explicitly labeled; compiler-derived types do not prove an undocumented "
             "precondition or algorithm guarantee. See the practical guide for expanded user-facing contracts.", "",
             "Generate the linked searchable HTML with `sbt \"figaro / Compile / doc\"`. Its relative links resolve "
             "in a local checkout after generation, not in GitHub's Markdown viewer. This Markdown reference itself "
             "is readable on GitHub without a build.", "", "## Packages and owners", ""]
    for package, methods in sorted(groups.items()):
        filename = package.replace("/", ".") + ".md"
        index.append(f"- [{package.replace('/', '.')}]({filename}) — {len(methods)} methods")
        lines = [MARKER, f"# {package.replace('/', '.')}", "", "[Reference index](README.md)", "",
                 "Examples are call templates: supply the named arguments with the declared types. "
                 "Context parameters are shown explicitly with `using`; defaults may be omitted in real calls. "
                 "`receiver` denotes an existing instance of the listed owner. Type parameters must be in scope. "
                 "Abstract members require a concrete implementation. The signature, not a template, is authoritative.", ""]
        for method in methods:
            live = api / method["page"]
            link = Path(os.path.relpath(live, output)).as_posix() + "#" + method["anchor"]
            lines += [f"## {markdown_code(method['owner'] + '.' + method['name'])}", "",
                      f"[Full Scaladoc entry]({link})", "", "```scala", method["signature"], "```", "",
                      method["summary"] or "No behavioral summary was supplied in the source Scaladoc; inspect the full entry and implementation before using this low-level API.", "",
                      "Type parameters: " + ("; ".join(markdown_code(t) for t in method["type_parameters"]) or "none") + ".", ""]
            if not method["parameter_lists"]:
                lines += ["Parameters: none (parameterless member; do not append `()`).", ""]
            for i, group in enumerate(method["parameter_lists"], 1):
                label = "Context parameters" if group["contextual"] else "Parameters"
                lines += [f"{label}, list {i}: " + ("; ".join(markdown_code(p) for p in group["parameters"]) or "none (empty argument list `()`)") + ".", ""]
            lines += ["Returns: " + markdown_code(method["returns"]) + ".", ""]
            if method["contract"] and method["contract"] != method["summary"]:
                lines += ["Source contract/attributes: " + method["contract"], ""]
            lines += ["Invocation template:", "", "```scala", method["example"], "```", ""]
        files[filename] = "\n".join(lines)
    files["README.md"] = "\n".join(index) + "\n"
    files["inventory.json"] = json.dumps({"schema": 1, "pages": page_count, "excluded_nonpublic": excluded,
                                           "methods": inventory}, indent=2, ensure_ascii=False) + "\n"
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--api-dir", type=Path, default=Path("target/out/jvm/scala-3.9.0/figaro/api"))
    parser.add_argument("--output", type=Path, default=Path("docs/api"))
    parser.add_argument("--check", action="store_true", help="read-only freshness check; fails on missing/stale files")
    parser.add_argument("--acl-script", type=Path, help="optional Windows PowerShell file-access verification hook, called immediately after creating/changing each item")
    args = parser.parse_args()
    api, output = args.api_dir.resolve(), args.output.resolve()
    files = render(api, output)

    def grant(path):
        if args.acl_script:
            shell = shutil.which("pwsh") or shutil.which("powershell")
            if not shell:
                raise ValueError("PowerShell is required for --acl-script")
            subprocess.run([shell, "-NoProfile", "-ExecutionPolicy", "Bypass", "-File",
                            str(args.acl_script.resolve()), "-Paths", str(path)], check=True, stdout=subprocess.DEVNULL)

    if not args.check and not output.exists():
        if not output.parent.is_dir():
            raise ValueError("Output parent must already exist")
        output.mkdir()
        grant(output)
    stale = []
    for name, text in files.items():
        path = output / name
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old == text:
            continue
        if args.check:
            stale.append(name)
        else:
            if old is not None and name != "inventory.json" and not old.startswith(MARKER):
                raise ValueError(f"Refusing to overwrite non-generated file: {path}")
            path.write_text(text, encoding="utf-8", newline="\n")
            grant(path)
    if output.exists():
        stale += [p.name for p in output.iterdir() if p.is_file() and p.name not in files]
    if stale:
        raise ValueError("Missing/stale reference files (regenerate; inspect obsolete files manually): " + ", ".join(stale))
    count = len(json.loads(files["inventory.json"])["methods"])
    print(f"{'Verified' if args.check else 'Generated'} {count} public method entries in {len(files)} files")


if __name__ == "__main__":
    try:
        main()
    except (ValueError, OSError) as error:
        sys.exit(str(error))
