"""Independent high-precision equations for the selected D5 representatives.

No production Scala implementation is imported. Scalars are differentiated from
their CDFs; count controls enumerate the joint; matrix/sphere controls use their
normalizers and independent low-dimensional integrals.
"""
import mpmath as mp


def scalar(kind, shape, p):
    xi=mp.mpf(str(shape)); u=mp.mpf(str(p)); mu=mp.mpf('.3'); scale=mp.mpf('1.7')
    if kind=='GEV':
        x=mu+scale*((-mp.log(u))**(-xi)-1)/xi if xi else mu-scale*mp.log(-mp.log(u))
        cdf=lambda v: mp.exp(-(1+xi*(v-mu)/scale)**(-1/xi)) if xi else mp.exp(-mp.exp(-(v-mu)/scale))
    else:
        x=mu+scale*((1-u)**(-xi)-1)/xi if xi else mu-scale*mp.log(1-u)
        cdf=lambda v: 1-(1+xi*(v-mu)/scale)**(-1/xi) if xi else 1-mp.exp(-(v-mu)/scale)
    return x,mp.log(mp.diff(cdf,x)),cdf(x)


def wishart(df, scale, x):
    d=scale.rows
    a=df*d/2*mp.log(2)+df/2*mp.log(mp.det(scale))+d*(d-1)/4*mp.log(mp.pi)+sum(mp.loggamma((df-i)/2) for i in range(d))
    return (df-d-1)/2*mp.log(mp.det(x))-sum((scale**-1*x)[i,i] for i in range(d))/2-a


def metric_values():
    p=mp.matrix([[2,mp.mpf('.3')],[mp.mpf('.3'),1]])
    q=mp.matrix([[1,mp.mpf('.1')],[mp.mpf('.1'),2]])
    def partition(n,s):
        return n*mp.log(2)+n/2*mp.log(mp.det(s))+mp.log(mp.pi)/2+mp.loggamma(n/2)+mp.loggamma((n-1)/2)
    elog=2*mp.log(2)+mp.log(mp.det(p))+mp.digamma(mp.mpf('2.5'))+mp.digamma(2)
    tr=sum((q**-1*p)[i,i] for i in range(2))
    kl=-mp.mpf('1.5')*elog+mp.mpf('2.5')*(tr-2)+partition(8,q)-partition(5,p)
    bh=(partition(5,p)+partition(8,q))/2-partition(mp.mpf('6.5'),((p**-1+q**-1)/2)**-1)
    lc=lambda k: mp.log(k/(4*mp.pi*mp.sinh(k))) if k else -mp.log(4*mp.pi)
    vmkl=lc(3)-lc(7)+3*(mp.coth(3)-mp.mpf(1)/3)
    vmbh=lc(mp.sqrt(58)/2)-(lc(3)+lc(7))/2
    gpdf=lambda x,xi: (1+xi*x)**(-1/xi-1)
    gp=lambda x: gpdf(x,mp.mpf('.1'))
    gq=lambda x: gpdf(x,mp.mpf('.2'))
    gkl=mp.quad(lambda x: gp(x)*mp.log(gp(x)/gq(x)),[0,1,mp.inf])
    gbh=-mp.log(mp.quad(lambda x: mp.sqrt(gp(x)*gq(x)),[0,1,mp.inf]))
    return dict(wishartLogDensity=wishart(mp.mpf(5),p,mp.matrix([[4,1],[1,3]])),wishartKl=kl,wishartBh=bh,vmfKl=vmkl,vmfBh=vmbh,gpdKl=gkl,gpdBh=gbh)


def scala_source():
    with mp.workdps(80):
        rows=[]
        for name in ('GEV','GPD'):
            for shape in (-2,-1,-.2,-1e-8,0,1e-8,.2,2):
                for p in (.13,.5,.91):
                    x,logpdf,cdf=scalar(name,shape,p)
                    rows.append(f'    ("{name}",{float(shape)!r},{float(p)!r},{float(x)!r},{float(logpdf)!r}),')
        values='\n'.join(f'  val {name}: Double = {float(value)!r}' for name,value in metric_values().items())
        return '// Generated by tools/breadth_reference.py; independent 80-digit controls.\npackage com.cra.figaro.test.modernization\n\nobject BreadthFixtures {\n  val scalars=Vector(\n'+'\n'.join(rows)+'\n  )\n'+values+'\n}\n'


if __name__=='__main__':
    import argparse
    from pathlib import Path
    parser=argparse.ArgumentParser(); parser.add_argument('--output',type=Path); args=parser.parse_args()
    if args.output: args.output.write_text(scala_source(),encoding='utf-8',newline='\n')
    else: print(scala_source(),end='')
