"""Independent mpmath==1.3.0 formulas; emits Scala fixtures, never writes files."""
import mpmath as mp


def continuous():
    return [('StudentT', [5.,.3,1.2]), ('StudentT',[.1,0.,1.]),
            ('Cauchy',[.2,1.3]), ('Laplace',[-.2,.7]), ('LogNormal',[.3,.8]),
            ('Weibull',[1.7,2.3]), ('Triangular',[-1.,.3,2.]), ('Kumaraswamy',[1.4,2.3])]


def law(name, params):
    """Return density, CDF, support and integration split points in multiprecision."""
    v=list(map(mp.mpf,params))
    if name == 'StudentT':
        nu,m,s=v
        def pdf(x): return (1+((x-m)/s)**2/nu)**(-(nu+1)/2)/(s*mp.sqrt(nu)*mp.beta(nu/2,.5))
        def cdf(x):
            tail=mp.betainc(nu/2,.5,0,nu/(nu+((x-m)/s)**2),regularized=True)/2
            return tail if x < m else 1-tail
        return pdf,cdf,(-mp.inf,mp.inf),[-mp.inf,m,mp.inf]
    if name == 'Cauchy':
        m,s=v
        return lambda x: 1/(mp.pi*s*(1+((x-m)/s)**2)),lambda x: .5+mp.atan((x-m)/s)/mp.pi,(-mp.inf,mp.inf),[-mp.inf,m,mp.inf]
    if name == 'Laplace':
        m,s=v
        return lambda x: mp.exp(-abs(x-m)/s)/(2*s),lambda x: mp.exp((x-m)/s)/2 if x <= m else 1-mp.exp(-(x-m)/s)/2,(-mp.inf,mp.inf),[-mp.inf,m,mp.inf]
    if name == 'LogNormal':
        m,s=v
        return lambda x: mp.exp(-(mp.log(x)-m)**2/(2*s*s))/(x*s*mp.sqrt(2*mp.pi)) if x>0 else mp.mpf(0),lambda x: mp.erfc((m-mp.log(x))/(s*mp.sqrt(2)))/2 if x>0 else mp.mpf(0),(0,mp.inf),[0,1,mp.inf]
    if name == 'Weibull':
        a,s=v
        return lambda x: a/s*(x/s)**(a-1)*mp.exp(-(x/s)**a) if x>0 else mp.mpf(0),lambda x: -mp.expm1(-(x/s)**a) if x>0 else mp.mpf(0),(0,mp.inf),[0,s,mp.inf]
    if name == 'Triangular':
        lo,m,hi=v
        def pdf(x):
            if not lo<x<hi: return mp.mpf(0)
            return 2*(x-lo)/((hi-lo)*(m-lo)) if x <= m else 2*(hi-x)/((hi-lo)*(hi-m))
        def cdf(x):
            if x <= lo: return mp.mpf(0)
            if x >= hi: return mp.mpf(1)
            return (x-lo)**2/((hi-lo)*(m-lo)) if x<=m else 1-(hi-x)**2/((hi-lo)*(hi-m))
        return pdf,cdf,(lo,hi),[lo,m,hi]
    if name == 'Kumaraswamy':
        a,b=v
        return lambda x: a*b*x**(a-1)*(1-x**a)**(b-1) if 0<x<1 else mp.mpf(0),lambda x: mp.mpf(0) if x<=0 else mp.mpf(1) if x>=1 else 1-(1-x**a)**b,(0,1),[0,.5,1]
    raise ValueError(name)


def fmt(x):
    if x == mp.inf: return 'Double.PositiveInfinity'
    if x == -mp.inf: return 'Double.NegativeInfinity'
    return repr(float(x))


def scala_source():
    with mp.workdps(70):
        lines=['package com.cra.figaro.test.modernization','',
               'import com.cra.figaro.library.atomic.continuous.*',
               'import com.cra.figaro.library.atomic.discrete.*','',
               '// Generated by tools/common_distribution_reference.py at 70 digits.',
               'private[modernization] object CommonDistributionFixtures {',
               '  val scalar: Vector[(ScalarDistribution,Double,Double,Double,Double)] = Vector(']
        rows=[]
        for name,params in continuous():
            pdf,cdf,support,_=law(name,params)
            points=[-.7,.2,.8,1.7,5.] if name != 'Kumaraswamy' else [.001,.2,.8,.999]
            for x in points:
                value=mp.mpf(x); c=cdf(value)
                rows.append('    ('+name+'Distribution('+','.join(map(fmt,params))+'),'+','.join(map(fmt,[x,mp.log(pdf(value)),c,1-c]))+')')
        for df,x in [(.001,1e300),(5.,1e300)]:
            pdf,cdf,_,_=law('StudentT',[df,0.,1.])
            tail=mp.betainc(mp.mpf(df)/2,.5,0,mp.mpf(df)/(mp.mpf(df)+mp.mpf(x)**2),regularized=True)/2
            rows.append('    (StudentTDistribution('+fmt(df)+'),'+','.join(map(fmt,[x,mp.log(pdf(mp.mpf(x))),1-tail,tail]))+')')
        lines.extend([',\n'.join(rows),'  )','  val count: Vector[(CountDistribution,Int,Double,Double)] = Vector('])
        rows=[]
        for r,p in [(2.5,.4),(.1,.9),(10.,.01)]:
            for k in [0,1,3,20,100]:
                r1,p1=mp.mpf(r),mp.mpf(p)
                logp=mp.loggamma(k+r1)-mp.loggamma(r1)-mp.loggamma(k+1)+r1*mp.log(p1)+k*mp.log1p(-p1)
                cdf=mp.betainc(r1,k+1,0,p1,regularized=True)
                rows.append('    (NegativeBinomialDistribution('+fmt(r)+','+fmt(p)+'),'+str(k)+','+fmt(logp)+','+fmt(cdf)+')')
        for n,s,d in [(20,7,5),(40,30,25)]:
            lo=max(0,d+s-n); hi=min(s,d)
            mass=lambda k: mp.binomial(s,k)*mp.binomial(n-s,d-k)/mp.binomial(n,d)
            for k in range(lo,hi+1):
                rows.append('    (HypergeometricDistribution('+','.join(map(str,[n,s,d]))+'),'+str(k)+','+fmt(mp.log(mass(k)))+','+fmt(sum(mass(j) for j in range(lo,k+1)))+')')
        lines.extend([',\n'.join(rows),'  )','}'])
        return '\n'.join(lines)+'\n'


if __name__ == '__main__':
    print(scala_source(),end='')
