"""GVM dependence reference: multiprecision harmonics and independent angular quadrature.

Optional mpmath==1.3.0; no production dependency or file writes.
"""
import mpmath as mp


def cases():
    """Named canonical beta/Gamma/concentration controls, including six dimensions."""
    return [
        ('independent', [0.], [[0.]], 4.),
        ('uniform', [1.], [[.2]], 0.),
        ('linear', [.4], [[0.]], 2.),
        ('weak', [1e-5], [[0.]], 50.),
        ('concentrated', [1.], [[0.]], 50.),
        ('curved', [.7], [[.3]], 4.),
        ('quadratic', [0.], [[1.2]], 8.),
        ('two', [.4,-.2], [[.3,.1],[.1,-.4]], 5.),
        ('six', [.2]*6, [[([.2,-.3,.4,-.5,.6,-.7][i] if i == j else 0.) for j in range(6)] for i in range(6)], 10.),
        ('broad', [8.], [[0.]], 4.),
        ('branch8', [0.]*8, [[(.7 if i == j else 0.) for j in range(8)] for i in range(8)], 2.),
        ('boundary32', [.1]*32, [[(0.2 if i == j else 0.) for j in range(32)] for i in range(32)], 5.)]


def coefficients(beta, gamma, kappa, terms=160):
    """Return normalized angular Fourier coefficients using current mp precision."""
    beta, gamma, k = mp.matrix(beta), mp.matrix(gamma), mp.mpf(kappa)
    values, vectors = mp.eigsy(gamma)
    projected = vectors.T*beta
    result = []
    for j in range(1, terms+1):
        log_phi = mp.mpc(0)
        for i in range(len(beta)):
            a = 1-1j*j*values[i]
            log_phi -= mp.log(a)/2+j*j*projected[i]**2/(2*a)
        result.append(mp.besseli(j,k)/mp.besseli(0,k)*mp.exp(log_phi))
    return result


def reference(beta, gamma, kappa, precision=60, terms=160):
    """Return MI in nats via high-precision Gauss-Legendre angular integration.

    This does not use the JVM's trapezoid rule, eigen precision or error heuristics.
    Exact-binary64 inputs enter through mp.mpf. Not a certified error enclosure.
    """
    with mp.workdps(precision):
        k = mp.mpf(kappa)
        if k == 0 or (not any(beta) and not any(any(row) for row in gamma)):
            return mp.mpf(0)
        cs = coefficients(beta, gamma, k, terms)
        upper = k*mp.besseli(1,k)/mp.besseli(0,k)-mp.log(mp.besseli(0,k))
        def integrand(theta):
            wave = mp.exp(-1j*theta)
            power, total = wave, mp.mpf(1)
            for c in cs:
                total += 2*mp.re(c*power)
                power *= wave
            if total <= 0:
                raise ArithmeticError('reference marginal positivity unresolved')
            return total*mp.log(total)
        deficit = mp.quadgl(integrand, [-mp.pi, -1, 0, 1, mp.pi])/(2*mp.pi)
        return upper-deficit


def scala_source():
    """Return Scala oracle fixtures; no file writes."""
    def vector(xs): return 'Vector('+','.join(repr(float(x)) for x in xs)+')'
    lines = ['package com.cra.figaro.test.modernization', '',
             '// Generated by tools/gvm_mutual_information_research.py; 60-digit quadrature.',
             'private[modernization] object GvmMutualInformationFixtures {',
             '  val all: Vector[(String,Vector[Double],Vector[Vector[Double]],Double,Double)] = Vector(']
    for index, (name,b,g,k) in enumerate(cases()):
        value = reference(b,g,k)
        lines.append('    ("'+name+'",'+vector(b)+',Vector('+','.join(vector(row) for row in g)+'),'+repr(k)+','+repr(float(value))+')'+(',' if index < len(cases())-1 else ''))
    return '\n'.join(lines+['  )','}'])+'\n'


if __name__ == '__main__':
    print(scala_source(), end='')
