"""Generate bounded Scala reliability fixtures with optional mpmath==1.3.0; stdout only.

Inputs are promoted from exact binary64 values to arbitrary precision, matching Scala
inputs. This is an oracle study, not production numerical certification.
"""
import math
from functools import lru_cache
import mpmath as mp
from gvm_bhattacharyya_research import Comparison, Kernel


def specifications():
    result = []
    for k in (.125,1.,10.,25.,40.,50.):
        for alpha in (0.,.5,2.,math.pi):
            for beta in (1e-5,.1,1.):
                result.append(('linear',1,k,alpha,beta,0.))
    for k in (1.,10.,25.,50.):
        for gamma in (.01,.5,2.):
            result.append(('unequal',1,k,0.,0.,gamma))
    for n in (2,6,16,32):
        for k in (1.,10.,50.):
            result.append(('dimension',n,k,0.,.2,.2))
    return result


def comparison(spec):
    family,n,k,alpha,beta,gamma = spec
    k,alpha,beta,gamma = (mp.mpf(v) for v in (k,alpha,beta,gamma))
    def kernel(mean,sd,a,b,g):
        return Kernel(mp.matrix([mp.mpf(mean)]*n),mp.mpf(sd)*mp.eye(n),mp.mpf(a),
                      mp.matrix([mp.mpf(b)]*n),mp.mpf(g)*mp.eye(n),k)
    if family == 'linear':
        return Comparison(kernel(0,1,0,0,0),kernel(0,1,alpha,beta,0))
    if family == 'unequal':
        return Comparison(kernel(.5,1,.25,.5,.25),kernel(-.5,.5,-.5,-.25,gamma))
    return Comparison(kernel(0,1,0,beta,gamma),kernel(0,1,0,-beta,0))


@lru_cache(maxsize=32)
def coefficients(k, precision, terms):
    with mp.workdps(precision):
        return tuple((1 if j == 0 else 2)*mp.besseli(j,k/2)**2/mp.besseli(0,k)
                     for j in range(terms+2))


def oracle(spec, precision=80, terms=128):
    with mp.workdps(precision):
        c = comparison(spec)
        weights = coefficients(mp.mpf(spec[2]),precision,terms)
        value = mp.fsum(weights[j]*mp.re(c.characteristic(j)) for j in range(terms+1))
        tail = weights[-1]/(1-c.a*c.b/(4*(terms+2)**2))
        if not value > 0 or tail/value > mp.mpf('1e-50'):
            raise ArithmeticError('oracle truncation or positivity check failed')
        return c.gaussian_distance-mp.log(value)


def scala_source():
    rows = []
    for index,spec in enumerate(specifications()):
        family,n,k,alpha,beta,gamma = spec
        expected = mp.nstr(oracle(spec),45)
        rows.append(f'    Fixture("{family}-{index:02d}","{family}",{n},{k!r},{alpha!r},{beta!r},{gamma!r},{expected})')
    return ('// Generated by tools/gvm_bhattacharyya_reliability.py at 80 decimal digits.\n'
            '// Fixed binary64 inputs; regeneration and independent positive controls are tested.\n'
            'package com.cra.figaro.test.modernization\n\n'
            'private[modernization] object GvmBhattacharyyaReliabilityFixtures {\n'
            '  final case class Fixture(id: String, family: String, n: Int, k: Double, alpha: Double,\n'
            '    beta: Double, gamma: Double, expected: Double)\n'
            '  val all: Vector[Fixture] = Vector(\n'+',\n'.join(rows)+'\n  )\n}\n')


if __name__ == '__main__':
    print(scala_source(),end='')
