"""Independent 80-digit angular-affinity fixtures for the test-only JVM cell bound."""
import math
import mpmath as mp
from gvm_bhattacharyya_reliability import comparison, specifications
from gvm_bhattacharyya_research import Comparison, scalar


def rows():
    """Return 108 exact-binary64 phase/concentration inputs with series reference affinities."""
    cases = []
    with mp.workdps(80):
        for spec in specifications():
            if spec[1] == 1:
                c = comparison(spec)
                cases.append(tuple(float(x) for x in (c.constant, c.linear[0], c.quadratic[0], c.p.kappa, c.q.kappa)))
        for phase in (math.nextafter(math.pi, -math.inf), math.pi, math.nextafter(math.pi, math.inf),
                      -math.pi, 3*math.pi, 10000.):
            for linear, quadratic, kp, kq in ((1e-5, 0., 50., 50.), (4., 2., 25., 50.),
                                               (-4., -2., .125, 50.), (10000., -10000., 50., 50.)):
                cases.append((phase, linear, quadratic, kp, kq))
        result = []
        for c, l, q, kp, kq in cases:
            p = scalar(alpha=mp.mpf(c), beta=mp.mpf(l), gamma=mp.mpf(q), kappa=mp.mpf(kp))
            reference, tail = Comparison(p, scalar(kappa=mp.mpf(kq))).series(128)
            assert reference > 0 and tail/reference < mp.mpf('1e-50')
            result.append((c, l, q, kp, kq, float(reference)))
        assert len(result) == 108
        return result


def scala_source():
    """Return generated Scala fixture source; no file writes."""
    lines = ['package com.cra.figaro.test.modernization', '',
             '// Generated by tools/gvm_scalar_cell_oracles.py; exact binary64 inputs, 80-digit series.',
             'private[modernization] object GvmScalarCellFixtures {',
             '  val all: Vector[(Double,Double,Double,Double,Double,Double)] = Vector(']
    lines += ['    ('+', '.join(repr(x) for x in row)+')'+(',' if i < 107 else '') for i, row in enumerate(rows())]
    return '\n'.join(lines+['  )', '}'])+'\n'


if __name__ == '__main__':
    print(scala_source(), end='')
