"""Held-out physical-input and radius/screen-boundary controls for scalar tail selection."""
import math
import random
import mpmath as mp
from gvm_bhattacharyya_research import Comparison, scalar


def rows():
    """Return 44 reproducible physical-kernel fixtures, tolerance and 80-digit distance."""
    cases = []
    # Phase-span screen at old radius 12: |beta|*12 + |gamma|*144 > 4.
    for label, beta, gamma in (('linear-screen', 4/12, 0.), ('quadratic-screen', 0., 4/144)):
        varying = beta or gamma
        for i, value in enumerate((math.nextafter(varying, -math.inf), varying, math.nextafter(varying, math.inf))):
            cases.append((f'{label}-{i}', 0., 1., 0., 1., .5, value if beta else 0., value if gamma else 0., 50., 50., 1e-8))
    with mp.workdps(80):
        boundary = float(16*mp.erfc(7/mp.sqrt(2))*mp.besseli(0, 10))
        for i, tolerance in enumerate((boundary*(1-1e-8), math.nextafter(boundary, -math.inf),
                                       boundary, math.nextafter(boundary, math.inf), boundary*(1+1e-8))):
            cases.append((f'radius-screen-{i}', 0., 1., 0., 1., .5, 1., .25, 10., 10., tolerance))
        rng = random.Random(20260908)
        for i in range(33):
            cases.append((f'holdout-{i:02d}', rng.uniform(-1,1), rng.uniform(.5,2),
                          rng.uniform(-1,1), rng.uniform(.5,2), rng.uniform(-math.pi,math.pi),
                          rng.uniform(-3,3), rng.uniform(-1,1), rng.uniform(.25,50), rng.uniform(.25,50), 1e-8))
        result = []
        for name, pm, ps, qm, qs, alpha, beta, gamma, kp, kq, tolerance in cases:
            # Scala constructs sd*sd in Double before kernel creation; model exactly that variance.
            p = scalar(mean=mp.mpf(pm), sd=mp.sqrt(mp.mpf(ps*ps)), kappa=mp.mpf(kp))
            q = scalar(mean=mp.mpf(qm), sd=mp.sqrt(mp.mpf(qs*qs)), alpha=mp.mpf(alpha),
                       beta=mp.mpf(beta), gamma=mp.mpf(gamma), kappa=mp.mpf(kq))
            c = Comparison(p, q)
            affinity, tail = c.series(128)
            assert affinity > 0 and tail/affinity < mp.mpf('1e-50')
            result.append((name, pm, ps, qm, qs, alpha, beta, gamma, kp, kq, tolerance,
                           float(c.gaussian_distance-mp.log(affinity))))
        assert len(result) == 44
        return result


def scala_source():
    """Return Scala source containing the complete held-out controls; no file writes."""
    lines = ['package com.cra.figaro.test.modernization', '',
             '// Generated by tools/gvm_scalar_tail_holdout.py; binary64 physical inputs, 80-digit series.',
             'private[modernization] object GvmScalarTailHoldoutFixtures {',
             '  case class Fixture(id: String,pm: Double,ps: Double,qm: Double,qs: Double,',
             '    alpha: Double,beta: Double,gamma: Double,kp: Double,kq: Double,tolerance: Double,expected: Double)',
             '  val all: Vector[Fixture] = Vector(']
    lines += ['    Fixture("'+row[0]+'", '+', '.join(repr(x) for x in row[1:])+')'+(',' if i < 43 else '')
              for i, row in enumerate(rows())]
    return '\n'.join(lines+['  )', '}'])+'\n'


if __name__ == '__main__':
    print(scala_source(), end='')
